apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-sw-tnps-     # <
labels:
  - includeSelectors: true
    pairs:
      app: sw-tnps     # <
      environment: production

namespace: devops-smart-website-ns     # <

resources:
- deployment.yaml
- ingress.yaml
- svc.yaml
- postgres

configMapGenerator:
  - name: larvl-cm
    literals:
      - ASSET_URL="tnps"     # <
      - APP_MAIN_ENV=production
      - APP_FORCE_HTTPS="true"
    envs:
      - .env

replacements:
  - source:
      name: larvl-svc
      kind: Service
      fieldPath: metadata.name
    targets:
      - select:
          name: larvl-ingress
          kind: Ingress
        fieldPaths:
          - spec.rules.0.http.paths.*.backend.service.name
  - source:
      name: db-svc
      kind: Service
      fieldPath: metadata.name
    targets:
      - select:
          name: larvl-cm
          kind: ConfigMap
        fieldPaths:
          - data.DB_HOST
  - source:
      name: larvl-cm
      kind: ConfigMap
      fieldPath: metadata.name
    targets:
      - select:
          name: larvl-deploy
        fieldPaths:
          - spec.template.spec.containers.[name=^apps$].envFrom.0.configMapRef.name
      - select:
          name: db-sfs
        fieldPaths:
          - spec.template.spec.containers.[name=^postgres$].envFrom.0.configMapRef.name


images:
  - name: apps-image-latest
    newName: registry.gitlab.com/smartaxiatakh/devops/smart-web-site/tnps/tnps
    newTag: staging-latest
    digest: sha256:81cba49a8af0105a23c80c5d28158ba5919f20461a4c41994f599b23457cce66
  - name: busybox
    newName: busybox
    newTag: 1.36.1-glibc
    digest: sha256:50aa4698fa6262977cff89181b2664b99d8a56dbca847bf62f2ef04854597cf8b7e4be4e9be38af6effd4f2271a93679de43bf8a634245d
