apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-sfs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql:latest
          envFrom:
            - configMapRef:
                name: "{{configMapName}}"
          env:
            - name: POSTGRESQL_DATABASE
              value: "$(DB_DATABASE)"
            - name: POSTGRESQL_USERNAME
              value: "$(DB_USERNAME)"
            - name: POSTGRESQL_PASSWORD
              value: "$(DB_PASSWORD)"
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          resources:
            requests:
              cpu: '500m'
              memory: '512Mi'
            limits:
              cpu: '1'
              memory: '1Gi'
          volumeMounts:
            - name: postgres-data
              mountPath: /bitnami/postgresql
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: freenas-nfs-csi
        resources:
          requests:
            storage: 5Gi
