apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartnas-static-asset
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
        - image: apps-image-latest
          imagePullPolicy: IfNotPresent
          name: smartnas-static-asset
          ports:
            - containerPort: 3000
              name: tcp3000
              protocol: TCP
          resources:
            requests:
              cpu: '250m'
              memory: '250Mi'
            limits:
              cpu: '500m'
              memory: '500Mi'
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: gitlab-registry-secret
      restartPolicy: Always
