apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: larvl-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: st-k8s-ingress.smart.com.kh
      http:
        paths:
          - path: /tnps(/|$)(.*)  # < sub-path is "st-k8s-ingress.smart.com.kh/tnps/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: "{{larvlSvcName}}"
                port:
                  number: 80
          - path: /tnps/tnps(/|$)(.*) # < match and resolve weird telescope, log-viwer, pulse asset url
            pathType: ImplementationSpecific
            backend:
              service:
                name: "{{larvlSvcName}}"
                port:
                  number: 80
  tls:
    - hosts:
        - st-k8s-ingress.smart.com.kh
      secretName: smart-tls-certificate
