apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: st-sw-tnps-
labels:
  - includeSelectors: true
    pairs:
      app: sw-tnps
      environment: staging

namespace: devops-smart-website-ns

resources:
- deployment.yaml
- svc.yaml
- postgres

configMapGenerator:
  - name: larvl-cm
    envs:
      - .env

replacements:
  - source:
      name: db-svc
      kind: Service
      fieldPath: metadata.name
    targets:
      - select:
          name: larvl-cm
          kind: ConfigMap
        fieldPaths:
          - data.DB_HOST
  - source:
      name: larvl-cm
      kind: ConfigMap
      fieldPath: metadata.name
    targets:
      - select:
          name: larvl-deploy
        fieldPaths:
          - spec.template.spec.containers.[name=^apps$].envFrom.0.configMapRef.name
      - select:
          name: db-sfs
        fieldPaths:
          - spec.template.spec.containers.[name=^postgres$].envFrom.0.configMapRef.name

images:
  - name: apps-image-latest
    newName: registry.gitlab.com/smartaxiatakh/devops/smart-web-site/tnps/tnps
    newTag: staging-latest
    digest: sha256:142cec8fffa2d739fa443d2d3646f8132c5d0aa23a7a8f5c2efe03ae3666aa8f
  - name: smartnas3-busybox
    newName: busybox
    newTag: 1.36.1-glibc
    digest: sha256:50aa4698fa6262977cff89181b2664b99d8a56dbca847bf62f2ef04854597cf8b7e4be4e9be38af6effd4f2271a93679de43bf8a634245d
