apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: st-sn4-gms-    # <
labels:
  - includeSelectors: true
    pairs:
#      app: gamification    # <
      environment: staging

namespace: devops-smartnas-ns      # <

resources:
- deployment.yaml
- ingress.yaml
- svc.yaml
- postgres

configMapGenerator:
  - name: apps-cm
    envs:
      - example.env
    literals:
#      - ASSET_URL="tnps" # <
      - APP_MAIN_ENV=staging
#      - APP_FORCE_HTTPS="true"

replacements:
  - source:
      name: apps-svc
      kind: Service
      fieldPath: metadata.name
    targets:
      - select:
          name: apps-ingress
          kind: Ingress
        fieldPaths:
          - spec.rules.0.http.paths.*.backend.service.name
  - source:
      name: db-svc
      kind: Service
      fieldPath: metadata.name
    targets:
      - select:
          name: apps-cm
          kind: ConfigMap
        fieldPaths:
          - data.DB_HOST
  - source:
      name: apps-cm
      kind: ConfigMap
      fieldPath: metadata.name
    targets:
      - select:
          name: apps-deploy
        fieldPaths:
          - spec.template.spec.containers.[name=^apps$].envFrom.0.configMapRef.name
      - select:
          name: db-sfs
        fieldPaths:
          - spec.template.spec.containers.[name=^postgres$].envFrom.0.configMapRef.name

images:
  - name: apps-image-latest
    newName: registry.gitlab.com/smartaxiatakh/devops/smartnas/services/gamification-service/staging
    newTag: UID-10
    digest: sha256:c4c734d5dc55ec95392883bc4f8badf454dd4deb667c1502086cca427eee6288
  - name: smartnas3-busybox
    newName: busybox
    newTag: 1.36.1-glibc
    digest: sha256:50aa4698fa6262977cff89181b2664b99d8a56dbca847bf62f2ef04854597cf8b7e4be4e9be38af6effd4f2271a93679de43bf8a634245d
