apiVersion: v1
kind: Service
metadata:
  name: smartnas-cms-backend-nodeport
spec:
  type: NodePort
  ports:
    - name: 80tcp
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30300