services:
  php:
    container_name: laravel-dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
      args:
        USER_ID: $UID
        GROUP_ID: $GID
    ports:
      - 8000:8080
    volumes:
      - ../:/var/www/html

  init-project:
    container_name: init-project
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: init-project
      args:
        USER_ID: $UID
        GROUP_ID: $GID
    ports:
      - 8000:8080
    volumes:
      - ../:/var/www/html
