
services:
    php:
        container_name: laravel-app
        build:
            context: ..
            dockerfile: docker/Dockerfile
            target: development
            args:
                USER_ID: $UID
                GROUP_ID: $GID
        environment:
            - PHP_FPM_POOL_NAME=laravel-app
            - AUTORUN_ENABLED=true
            - AUTORUN_LARAVEL_MIGRATION=true
            - SSL_MODE=off # off, mixed, full
        ports:
            - 8000:8080
        volumes:
            - ../:/var/www/html

    prod:
        container_name: laravel-app
        image: ${IMAGE_LATEST}
        environment:
            - PHP_FPM_POOL_NAME=laravel-app
            - AUTORUN_ENABLED=true
            - AUTORUN_LARAVEL_MIGRATION=true
            - SSL_MODE=off # off, mixed, full
        ports:
            - 8000:8080
#        env_file:
#            - ../.env

    postgres:
        image: bitnami/postgresql:latest
        container_name: dev_postgres
        environment:
            POSTGRESQL_USERNAME: ${DB_USERNAME}
            POSTGRESQL_PASSWORD: ${DB_PASSWORD}
            POSTGRESQL_DATABASE: ${DB_DATABASE}
        ports:
            - "5432:5432"
#        env_file:
#            - ../.env
#        volumes:
#            - postgres_data:/bitnami/postgresql

    init-project:
        container_name: laravel-app
        build:
            context: ..
            dockerfile: docker/Dockerfile
            target: init-project
            args:
                USER_ID: $UID
                GROUP_ID: $GID
        ports:
            - 8000:8080
        volumes:
            - ../:/var/www/html

#volumes:
#    postgres_data:
