services:
  php:
    container_name: laravel-dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
      args:
        USER_ID: $UID
        GROUP_ID: $GID
    ports:
      - 8000:8080
    volumes:
      - ../:/var/www/html

  init-project:
    container_name: init-project
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: init-project
      args:
        USER_ID: $UID
        GROUP_ID: $GID
    ports:
      - 8000:8080
    volumes:
      - ../:/var/www/html

  postgres:
    image: bitnami/postgresql:latest
    container_name: dev_postgres
    environment:
        POSTGRESQL_USERNAME: dev_user
        POSTGRESQL_PASSWORD: dev_password
        POSTGRESQL_DATABASE: dev_db
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/bitnami/postgresql

# volumes:
#   postgres_data: