apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: pgsql-
labels:
  - includeSelectors: true
    pairs:
      app: postgres-db
      environment: staging

resources:
  - statefulset.yaml
  - svc.yaml
